name: food_app_flutter_zone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  scoped_model: ^1.0.1
  rxdart: ^0.24.1
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/beer.png
    - assets/images/breakfast.jpeg
    - assets/images/burger.png
    - assets/images/cheeseburger.png
    - assets/images/coffee-cup.png
    - assets/images/cupcake.png
    - assets/images/lunch.jpeg
    - assets/images/pizza.png
    - assets/images/supper_1.jpeg
    - assets/images/turkey.png
    - assets/images/noimage.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true